# Generated by Django 5.2.6 on 2025-09-03 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_code', models.CharField(db_index=True, max_length=50)),
                ('date', models.DateField(db_index=True)),
                ('high', models.DecimalField(decimal_places=4, max_digits=20, null=True)),
                ('low', models.DecimalField(decimal_places=4, max_digits=20, null=True)),
                ('open', models.DecimalField(decimal_places=4, max_digits=20, null=True)),
                ('close', models.DecimalField(decimal_places=4, max_digits=20, null=True)),
                ('volume', models.BigIntegerField(null=True)),
            ],
        ),
    ]
